### ISSUE TITLE
Help to add invert color option in hovacui

### ISSUE THREAD

**Issue by roomroofroot** [sgerwk/pdftoroff#2]
Hi there. Thanks for the great work, I have been a big fan of this project, especially the hovacui reader (its simple and minimal yet functional, along with X and fb support).

Is it possible to add an option to invert the colors of the pdf (like mupdf/zathura do)?
I'm not great with poppler headers, and need some help figuring out if possible to add an invert-color option. 

Please check this out when you have the time to do so.
Thank you.

**Comment by sgerwk** [comment]
That's a good idea, indeed.

Implemented in d28a9aa44de4233aee67f461db5b8e0dbc866136, check it out.

**Comment by sgerwk** [comment]
Forgot to say:

hovacui -c night file.pdf

or add "night" to .config/hovacui/hovacui.conf

**Comment by roomroofroot** [comment]
It works very well!
Thank you very much for your time and effort, and also for responding quickly.
